# Setup
title:               simst.im
tagline:             ''
description:         'Blog of Benjamin Eckel'
url:                 https://bhelx.simst.im
baseurl:             ''
permalink:           none

# About/contact
author:
  name:              Benjamin Eckel
  url:               https://bhelx.simst.im
  email:             bhelx@simst.im

# Custom vars
version:             1.1.0

plugins:
  - jekyll-compress-images

compress_images:
  images_path: "public/images/**/*.{gif,png,jpg,jpeg}"
