# Setup
title:               simst.im
tagline:             ''
description:         'Blog of Benjamin Eckel'
url:                 https://bhelx.simst.im
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Benjamin Eckel
  url:               https://bhelx.simst.im
  email:             bhelx@simst.im

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
